version: '3.4'

services:
  ecommerce:
    image: ${DOCKER_REGISTRY-}ecommerce
    expose:
        - "5000"
    environment:
        - IdentityServer=http://127.0.0.1:5103/
        - ProductsUrl=http://127.0.0.1:5102/
        - AccountUrl=https://127.0.0.1:5101/
    build:
      context: .
      dockerfile: src/Web/Ecommerce/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - identityserver
        - useraccountapi
        - productsapi
         
  useraccountapi:
    image: ${DOCKER_REGISTRY-}useraccountapi
    expose:
        - "80"
    ports:
        - "5101:80" 
    build:
      context: .
      dockerfile: src/Services/UserAccountApi/Dockerfile
    


  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    ports:
      - "5102:80" 
    build:
      context: .
      dockerfile: src/Services/ProductsApi/Dockerfile
    

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    ports:
        - "5103:80" 
    build:
      context: .
      dockerfile: src/Services/IdentityServer/Dockerfile
    
